TRUNCATE TABLE "RECEPCIONISTA" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "PEDIDO" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "DELIVERY" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "STATUS_DELIVERY" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "FORMAS_PAGAMENTO" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CARDAPIO" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "CLIENTE" RESTART IDENTITY CASCADE;
